version: Build {build}

skip_non_tags: true

build:
    verbosity: minimal

environment:
    matrix:
        - MINICONDA_VERSION: "latest"
          PYTHON: "C:\\Miniconda36-x64"
          PYTHON_VERSION: "3.6"
          platform: x64
          PYTHON_ARCH: "64"
          CONDA_DEPENDENCIES: "scipy"

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "python --version"
    - "pip install -r requirements.txt"
    - "pip install pypiwin32>=223"
    # PyInstaller-3.3.dev0+g964547cd
    - "pip --version"
    - "python -m pip install -U \"pip<19.0\""
    - "pip --version"
    - "pip install git+git://github.com/pyinstaller/pyinstaller.git@develop"

build_script:
    - "python -c \"from pycamv import proteowizard ; proteowizard.fetch_proteowizard()\""
    - "pyinstaller pycamv.spec"

test_script:
    - "python setup.py test"

artifacts:
    - path: dist\PyCAMVerter.exe
      name: PyCAMVerter

deploy:
    - provider: GitHub
      description: "Tool for processing mass spectrometry data for CAMV"
      artifact: PyCAMVerter
      draft: false
      prerelease: false
      force_update: true
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: +GzJ//tQ7T8IYqT0tFSseDQ7N5+HfGrh6pv4DHVTMxy3fhd5KYYXUfhgXkqoCIfn
